services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - casecellshop-data:/app/data

  frontend:
    build:
      context: ./Frontend/case-cell-shop-webapp
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  casecellshop-data: